table Measure
	lineageTag: 899c73cd-7f28-4bab-8e68-0ed1ec8267c0

	measure 'Total Population' =
			CALCULATE(
			        SUM('Fact World Bank Data'[total_population]),
			        TREATAS(VALUES('Dim Reference Year'[Year]), 'Dim Year'[year])
			    )
		formatString: #,0
		lineageTag: 5de338c1-3afb-4b99-99f8-7fa9fc8428e9

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Poverty Headcount Ratio (%)' =
			CALCULATE(
			        IF(
			            HASONEVALUE('Fact World Bank Data'[country]),
			            AVERAGE('Fact World Bank Data'[poverty_headcount_ratio]),
			            DIVIDE(
			                SUMX(
			                    FILTER('Fact World Bank Data', NOT ISBLANK('Fact World Bank Data'[poverty_headcount_ratio])),
			                    'Fact World Bank Data'[poverty_headcount_ratio] * 'Fact World Bank Data'[total_population]
			                ),
			                SUMX(
			                    FILTER('Fact World Bank Data', NOT ISBLANK('Fact World Bank Data'[poverty_headcount_ratio])),
			                    'Fact World Bank Data'[total_population]
			                )
			            )
			        ) / 100,
			        TREATAS(VALUES('Dim Reference Year'[Year]), 'Dim Year'[year])
			    )
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: a0e114fb-23ba-4a7b-bf65-6cca3422df5d

	measure 'GDP per Capita (PPP)' =
			CALCULATE(
			        IF(
			            HASONEVALUE('Fact World Bank Data'[country]),
			            AVERAGE('Fact World Bank Data'[gdp_per_capita]),
			            DIVIDE(
			                SUMX(
			                    FILTER('Fact World Bank Data', NOT ISBLANK('Fact World Bank Data'[gdp_per_capita])),
			                    'Fact World Bank Data'[gdp_per_capita] * 'Fact World Bank Data'[total_population]
			                ),
			                SUMX(
			                    FILTER('Fact World Bank Data', NOT ISBLANK('Fact World Bank Data'[gdp_per_capita])),
			                    'Fact World Bank Data'[total_population]
			                )
			            )
			        ),
			        TREATAS(VALUES('Dim Reference Year'[Year]), 'Dim Year'[year])
			    )
		formatString: #,0
		lineageTag: 1271a108-b46f-43ae-8f66-be626ca4cc2d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'GDP per Capita Growth Trend' = ```
			
			    -- Se elimina el REMOVEFILTERS porque la tabla ya está desconectada físicamente
			    IF(
			        HASONEVALUE('Fact World Bank Data'[country]),
			        AVERAGE('Fact World Bank Data'[gdp_per_capita_growth]),
			        DIVIDE(
			            SUMX(
			                FILTER('Fact World Bank Data', NOT ISBLANK('Fact World Bank Data'[gdp_per_capita_growth])),
			                'Fact World Bank Data'[gdp_per_capita_growth] * 'Fact World Bank Data'[total_population]
			            ),
			            SUMX(
			                FILTER('Fact World Bank Data', NOT ISBLANK('Fact World Bank Data'[gdp_per_capita_growth])),
			                'Fact World Bank Data'[total_population]
			            )
			        )
			    ) / 100
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: b924ec27-4b1d-480c-8be2-691320434aab

	measure 'GDP per Capita (PPP) Highlighted Color' =
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE('Dim Reference Year'[Year]) = SELECTEDVALUE('Dim Year'[year]) && [GDP per Capita Growth Trend] < 0, "#B22222",
			        SELECTEDVALUE('Dim Reference Year'[Year]) = SELECTEDVALUE('Dim Year'[year]), "#118DFF",
			        [GDP per Capita Growth Trend] < 0, "#FFB3B3",
			        "#CFE7FF"
			    )
		lineageTag: 9a824427-d14a-4e27-a1d0-64aeeccc1de6

	measure 'GDP per Capita Growth (Annual %)' =
			CALCULATE(
			        IF(
			            HASONEVALUE('Fact World Bank Data'[country]),
			            AVERAGE('Fact World Bank Data'[gdp_per_capita_growth]),
			            DIVIDE(
			                SUMX(
			                    FILTER('Fact World Bank Data', NOT ISBLANK('Fact World Bank Data'[gdp_per_capita_growth])),
			                    'Fact World Bank Data'[gdp_per_capita_growth] * 'Fact World Bank Data'[total_population]
			                ),
			                SUMX(
			                    FILTER('Fact World Bank Data', NOT ISBLANK('Fact World Bank Data'[gdp_per_capita_growth])),
			                    'Fact World Bank Data'[total_population]
			                )
			            )
			        ) / 100,
			        TREATAS(VALUES('Dim Reference Year'[Year]), 'Dim Year'[year])
			    )
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 38cbdbb6-bd97-46ea-9125-bcaeba9b66af

	measure 'Global GDP per Capita (PPP)' =
			CALCULATE(
			        IF(
			            HASONEVALUE('Fact World Bank Data'[country]),
			            AVERAGE('Fact World Bank Data'[gdp_per_capita]),
			            DIVIDE(
			                SUMX(
			                    FILTER('Fact World Bank Data', NOT ISBLANK('Fact World Bank Data'[gdp_per_capita])),
			                    'Fact World Bank Data'[gdp_per_capita] * 'Fact World Bank Data'[total_population]
			                ),
			                SUMX(
			                    FILTER('Fact World Bank Data', NOT ISBLANK('Fact World Bank Data'[gdp_per_capita])),
			                    'Fact World Bank Data'[total_population]
			                )
			            )
			        ),
			        REMOVEFILTERS('Dim Country'[country_code], 'Dim Country'[country_name]),
			        TREATAS(VALUES('Dim Reference Year'[Year]), 'Dim Year'[year])
			    )
		lineageTag: f88276b4-d468-4c3f-9c95-cfb24734f65a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Goblal GDP per Capita (PPP) Trend' =
			CALCULATE(
			        IF(
			            HASONEVALUE('Fact World Bank Data'[country]),
			            AVERAGE('Fact World Bank Data'[gdp_per_capita]),
			            DIVIDE(
			                SUMX(
			                    FILTER('Fact World Bank Data', NOT ISBLANK('Fact World Bank Data'[gdp_per_capita])),
			                    'Fact World Bank Data'[gdp_per_capita] * 'Fact World Bank Data'[total_population]
			                ),
			                SUMX(
			                    FILTER('Fact World Bank Data', NOT ISBLANK('Fact World Bank Data'[gdp_per_capita])),
			                    'Fact World Bank Data'[total_population]
			                )
			            )
			        ),
			        REMOVEFILTERS('Dim Country'[region],'Dim Country'[country_code],'Dim Country'[country_name])
			    )
		lineageTag: 392952b5-3701-46d1-bbd3-26057fbd819c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Economies' =
			CALCULATE(
			        DISTINCTCOUNT('Fact World Bank Data'[country_code]),
			        TREATAS(VALUES('Dim Reference Year'[Year]), 'Dim Year'[year])
			    )
		formatString: 0
		lineageTag: b295b04a-ea2b-490f-958c-3c76504a751f

	measure 'Economy in Focus' =
			SWITCH(
			        TRUE(),
			        HASONEVALUE('Dim Country'[country_name]), SELECTEDVALUE('Dim Country'[country_name]),
			        HASONEVALUE('Dim Country'[region]), "regional",
			        "global"
			    )
		lineageTag: d38db0c3-9d21-49ce-ac6f-fd047ad64bc6

	measure 'Population Share (% of World Population)' =
			DIVIDE(
			        [Total Population],
			        CALCULATE([Total Population], ALL('Dim Country'))
			    )
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 0d966aaf-667d-40d2-9bad-e3088698d469

	measure 'GDP Share (% of Global GDP)' =
			DIVIDE(
			        [GDP (PPP)],
			        CALCULATE([GDP (PPP)], ALL('Dim Country'))
			    )
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 3c167ba4-5a67-487e-a200-a171e60f9a5a

	measure 'GDP per Capita Growth Highlighted Value' =
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE('Dim Reference Year'[Year]) = SELECTEDVALUE('Dim Year'[year]), [GDP per Capita Growth (Annual %)],
			        BLANK()
			    )
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 9956f2fb-b0e9-487a-8b17-045592d35970

	measure 'GDP (PPP)' =
			CALCULATE(
			        SUM('Fact World Bank Data'[gdp]),
			        TREATAS(VALUES('Dim Reference Year'[Year]), 'Dim Year'[year])
			    )
		formatString: #,0
		lineageTag: 1fd4d921-191c-4ded-95ae-4f6428b6d479

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'World Population Display' =
			VAR _Population = [Total Population]
			    VAR _IsCountryFiltered = HASONEVALUE('Dim Country'[country_name])
			    VAR _DisplayValue = SWITCH(
			        TRUE(),
			        _IsCountryFiltered && _Population < 100000, _Population / 1000,
			        _IsCountryFiltered, _Population / 1000000,
			        (_Population / 1000000000) * 1000
			    )
			    VAR _Suffix = SWITCH(TRUE(), _IsCountryFiltered && _Population < 100000, " K", " M")
			    RETURN FORMAT(ROUNDDOWN(_DisplayValue, 1), "#,0.0") & _Suffix
		lineageTag: a27c046f-9d89-4cc5-af78-9bd9f6b69a60

	measure 'Global Income Position' =
			VAR EconomyValue = [GDP per Capita (PPP)]
			    VAR GlobalAverage = CALCULATE([GDP per Capita (PPP)], ALL('Dim Country'))
			    RETURN SWITCH(
			        TRUE(),
			        EconomyValue >= GlobalAverage, "Above global average income",
			        "Below global average income"
			    )
		lineageTag: e64ea290-bf7c-4488-82c8-90583df23ab0
		dataCategory: ImageUrl

	measure 'GDP per Capita (PPP) Trend' =
			VAR _CountryToUse =
			    IF(
			        HASONEVALUE('Dim Country'[country_name]),
			        [Economy in Focus],
			        [Country with Highest GDP per Capita]
			    )
			    RETURN
			    CALCULATE(
			        IF(
			            HASONEVALUE('Fact World Bank Data'[country]),
			            AVERAGE('Fact World Bank Data'[gdp_per_capita]),
			            DIVIDE(
			                SUMX(
			                    FILTER('Fact World Bank Data', NOT ISBLANK('Fact World Bank Data'[gdp_per_capita])),
			                    'Fact World Bank Data'[gdp_per_capita] * 'Fact World Bank Data'[total_population]
			                ),
			                SUMX(
			                    FILTER('Fact World Bank Data', NOT ISBLANK('Fact World Bank Data'[gdp_per_capita])),
			                    'Fact World Bank Data'[total_population]
			                )
			            )
			        ),
			        FILTER(
			            ALL('Dim Country'),
			            'Dim Country'[country_name] = _CountryToUse
			        )
			    )
		lineageTag: d16d5b8a-406f-40be-bd12-3a5de8f13cc7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Year Highlighted Value' = MAX('Dim Reference Year'[Year])
		formatString: 0
		lineageTag: 17ebb7a6-82c3-46ab-a023-22255a458d5c

	measure 'Legend Placeholder' = 1
		formatString: 0
		lineageTag: a36b7f49-fb0f-41a5-a756-5620edf01d7b

	measure 'GDP per Capita Highlighted Value' =
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE('Dim Reference Year'[Year]) = SELECTEDVALUE('Dim Year'[year]), [GDP per Capita (PPP)],
			        BLANK()
			    )
		lineageTag: 901248e8-62ea-40d5-bb3f-bcf78ddd0afa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Country with Highest GDP per Capita' =
			CALCULATE(
			        MAXX(
			            TOPN(1, 'Dim Country', [GDP per Capita (PPP)], DESC),
			            'Dim Country'[country_name]
			        )
			    )
		lineageTag: 5451bdf7-2d90-4460-970a-21b1b503bbf3

	measure 'Benchmark Economy' =
			SWITCH(
			        TRUE(),
			        HASONEVALUE('Dim Country'[country_name]), [Economy in Focus],
			        [Country with Highest GDP per Capita]
			    )
		lineageTag: 8f2621c7-4eda-43c0-aec0-fb1652bd889e

	measure 'Economic Scope Label' = IF(HASONEVALUE('Dim Country'[country_name]), "Economy", "Economies")
		lineageTag: 4975de68-55b1-4031-bd34-b70546b94e24

	measure 'GDP per Capita Rank' =
			
			VAR _Rank =
			    CALCULATE(
			        RANKX(
			            ALL('Dim Country'[country_code],'Dim Country'[region]),
			            [GDP per Capita (PPP)],
			            ,
			            DESC,
			            DENSE
			        )
			    )
			
			RETURN
			IF(
			    HASONEVALUE('Dim Country'[country_name]),
			    _Rank,
			    1
			)
		formatString: 0
		lineageTag: 58a38b1a-0974-4988-8e66-e3875571cf18

	measure 'GDP per Capita Ranking Narrative' =
			
			VAR _Rank =
			    [GDP per Capita Rank]
			
			VAR _MinYear =
			    MIN('Dim Reference Year'[Year])
			
			VAR _MaxYear =
			    MAX('Dim Reference Year'[Year])
			
			VAR _YearLabel =
			    IF(
			        _MinYear = _MaxYear,
			        FORMAT(_MinYear, "0"),
			        FORMAT(_MinYear, "0") & "–" & FORMAT(_MaxYear, "0")
			    )
			
			RETURN
			"Ranked #" & FORMAT(_Rank, "0") &
			" globally in GDP per capita (PPP) during " &
			_YearLabel & "."
		lineageTag: c229c0d5-59a0-49e3-8019-2dc2c50f9b0a

	measure 'Population Share Heatmap Color' =
			
			VAR _Value = [Population Share (% of World Population)]
			
			RETURN
			    SWITCH(
			        TRUE(),
			
			        ISBLANK(_Value), "#FFFFFF",
			
			        _Value <= -0.40, "#B00020",
			        _Value <= -0.30, "#D32F2F",
			        _Value <= -0.20, "#EF5350",
			        _Value <= -0.15, "#E57373",
			        _Value <= -0.10, "#EF9A9A",
			        _Value <= -0.05, "#FFCDD2",
			        _Value < 0, "#FDECEF",
			
			        _Value = 0, "#FFFFFF",
			
			        _Value <= 0.05, "#F3F9FF",
			        _Value <= 0.10, "#E1F0FF",
			        _Value <= 0.15, "#CBE4FF",
			        _Value <= 0.20, "#A9D2FF",
			        _Value <= 0.25, "#7BB9FF",
			        _Value <= 0.30, "#4DA3FF",
			        _Value <= 0.40, "#118DFF",
			        _Value <= 0.50, "#006EDC",
			
			        "#004EB0"
			    )
		lineageTag: f0df749f-8d00-489e-b910-271f484ad122

	measure 'GDP Share Heatmap Color' =
			
			VAR _Value = [GDP Share (% of Global GDP)]
			
			RETURN
			    SWITCH(
			        TRUE(),
			
			        ISBLANK(_Value), "#FFFFFF",
			
			        _Value <= -0.40, "#B00020",
			        _Value <= -0.30, "#D32F2F",
			        _Value <= -0.20, "#EF5350",
			        _Value <= -0.15, "#E57373",
			        _Value <= -0.10, "#EF9A9A",
			        _Value <= -0.05, "#FFCDD2",
			        _Value < 0, "#FDECEF",
			
			        _Value = 0, "#FFFFFF",
			
			        _Value <= 0.05, "#F3F9FF",
			        _Value <= 0.10, "#E1F0FF",
			        _Value <= 0.15, "#CBE4FF",
			        _Value <= 0.20, "#A9D2FF",
			        _Value <= 0.25, "#7BB9FF",
			        _Value <= 0.30, "#4DA3FF",
			        _Value <= 0.40, "#118DFF",
			        _Value <= 0.50, "#006EDC",
			
			        "#004EB0"
			    )
		lineageTag: 6876a670-f035-4856-8e64-61a520ec25ac

	measure 'Poverty Headcount Ratio Heatmap Color' =
			
			VAR _Value = [Poverty Headcount Ratio (%)]
			
			RETURN
			    SWITCH(
			        TRUE(),
			
			        ISBLANK(_Value), "#FFFFFF",
			
			        _Value <= -0.40, "#B00020",
			        _Value <= -0.30, "#D32F2F",
			        _Value <= -0.20, "#EF5350",
			        _Value <= -0.15, "#E57373",
			        _Value <= -0.10, "#EF9A9A",
			        _Value <= -0.05, "#FFCDD2",
			        _Value < 0, "#FDECEF",
			
			        _Value = 0, "#FFFFFF",
			
			        _Value <= 0.05, "#F3F9FF",
			        _Value <= 0.10, "#E1F0FF",
			        _Value <= 0.15, "#CBE4FF",
			        _Value <= 0.20, "#A9D2FF",
			        _Value <= 0.25, "#7BB9FF",
			        _Value <= 0.30, "#4DA3FF",
			        _Value <= 0.40, "#118DFF",
			        _Value <= 0.50, "#006EDC",
			
			        "#004EB0"
			    )
		lineageTag: a7c70544-8181-431d-ae60-01b9e52cd5cc

	partition Measure = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

